### ISSUE TITLE
error: ...acf.php): failed to open stream: No such file or directory ...

### ISSUE THREAD

**Issue by jimoquinn** [jessecowens/jco-asciinema-player#5]
Warning: require_once(/var/www/html/wp-content/plugins/jco-asciinema-player-master/includes/acf/acf.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/jco-asciinema-player-master/includes/class-jco-asciinema-player.php on line 129

**Comment by jessecowens** [comment]
Hello @jimoquinn,
Sorry for the late reply.
If you're installing this plugin via git and not via the WordPress Repository, you'll need to initialize the ACF submodule. After cloning, run the following commands:
```
git submodule init
git submodule update
```
